# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Qing Li
name: Qing Li
position:
email: qingleoli@gmail.com
description: >-
  I am an associate researcher at the [School of Computing and Artificial Intelligence, Southwest Jiaotong University](https://scai.swjtu.edu.cn).
  Before that, I was a postdoctoral fellow at the [School of Software, Tsinghua University](https://www.thss.tsinghua.edu.cn/).
  I received my doctoral degree from the [School of Informatics, Xiamen University](https://informatics.xmu.edu.cn/).


  My research interests include 3D computer vision and point cloud processing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "leoqli.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username: LeoQLi
google_scholar: 91Mm7vgAAAAJ
google_analytics: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
